# Database configuration
# Example:
# db.url=jdbc:mysql://YOUR_HOST:3306/blood_archive?useSSL=false&serverTimezone=UTC
# db.user=YOUR_USER
# db.pass=YOUR_PASSWORD

db.url=jdbc:mysql://localhost:3306/blood_archive?useSSL=false&serverTimezone=UTC
db.user=root
db.pass=Kishin122912
